name: SonarQube Scan for Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests & generate coverage (optional)
        run: |
          pytest --cov=. --cov-report=xml

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=https://sonarcloud.io